const REQUEST_PRODUCTS_IS_LOADING = 'REQUEST_PRODUCTS_IS_LOADING';
const REQUEST_PRODUCTS_IS_ERROR = 'REQUEST_PRODUCTS_IS_ERROR';
const REQUEST_PRODUCTS_SUCCESS = 'REQUEST_PRODUCTS_SUCCESS';
const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
const FILTER_PRODUCTS = 'FILTER_PRODUCTS';

export default{
    REQUEST_PRODUCTS_IS_LOADING,
    REQUEST_PRODUCTS_IS_ERROR,
    REQUEST_PRODUCTS_SUCCESS,
    FETCH_PRODUCTS,
    FILTER_PRODUCTS
}